### ISSUE TITLE
autoriser deux réseaux wifi

### ISSUE THREAD

**Issue by zb2oby** [rol25/Yana4All#1]
Hello,

Est-il possible d'autoriser deux reseaux sur l'appli. En effet j'ai une grande maison en pierre qui necessite un second réseau via un répéteur et du coup un second ssid. sauf que lorsque mon terminal android switch de réseau tout seul je ne peut plus me connecter sur l'appli. Je ne sait pas si je suis le seul dans ce cas la. Merci à toi

**Comment by rol25** [comment]
Bonjour,
Pourquoi ne pas simplement donner le même ssid au vos deux points d'accès ?
C'est ce que je fais chez moi.
Amicalement,
Alexandre.

**Comment by zb2oby** [comment]
Pas bête. Je ne pensais même pas que cela étais possible. Je pensais que ça pouvais créer des conflits. Mais je vais faire ça du coup. Merci beaucoup.

**Comment by rol25** [comment]
Derien ^^.
Si jamais n'hésitez pas
Amicalement,
Alexandre.

Le 10 août 2017 15:39, "zb2oby" <notifications@github.com> a écrit :

Pas bête. Je ne pensais même pas que cela étais possible. Je pensais que ça
pouvais créer des conflits. Mais je vais faire ça du coup. Merci beaucoup.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rol25/Yana4All/issues/1#issuecomment-321553660>, or mute
the thread
